[build]
target = "riscv32im-unknown-none-elf"

[target.riscv32im-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.ld",
    "-C", "link-arg=--no-relax",
]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]


